import eyeIcon from "../../src/assets/images/svg/eyeicon.png";
import { IconButton } from "@mui/material";
import { StatusText } from "./CommonRowColumnUtils.styled";

const StatusCell = (params) => (
  <StatusText statuscolor={params.row.statusColor}>{params.value}</StatusText>
);

const ActionCell = () => (
  <IconButton size="small" color="primary">
    <img src={eyeIcon} alt="view" width={16} height={16} />
  </IconButton>
);

export const UserManagementColumnData = [
  {
    field: "carrierId",
    headerName: "Carrier ID",
    width: 50,
    minWidth: 150,
    maxWidth: 220,
    headerTooltip: true,
    cellClassName: "sticky-col-left-1",
    headerClassName: "sticky-col-left-1",
  },
  {
    field: "carrierName",
    headerName: "Carrier Name",
    width: 180,
    minWidth: 150,
    maxWidth: 220,
    headerTooltip: true,
    cellClassName: "sticky-col-left-2",
    headerClassName: "sticky-col-left-2",
  },
  {
    field: "userProfile",
    headerName: "User Profile",
    flex: 1,
    minWidth: 150,
    maxWidth: 220,
    headerTooltip: true,
  },
  {
    field: "firstName",
    headerName: "First Name",
    flex: 1,
    minWidth: 180,
    maxWidth: 250,
    headerTooltip: true,
  },
  {
    field: "lastName",
    headerName: "Last Name",
    flex: 1,
    minWidth: 180,
    maxWidth: 250,
    headerTooltip: true,
  },
  {
    field: "createdOn",
    headerName: "Created ON",
    flex: 1,
    minWidth: 180,
    maxWidth: 250,
    headerTooltip: true,
  },
  {
    field: "updatedOn",
    headerName: "Updated ON",
    flex: 1,
    minWidth: 180,
    maxWidth: 250,
    headerTooltip: true,
  },
  {
    field: "primaryContactEmail",
    headerName: "Primary Contact Email",
    minWidth: 180,
    maxWidth: 250,
    flex: 1,
    headerTooltip: true,
    // align: "center",
    // headerAlign: "center",
  },

  {
    field: "status",
    headerName: "Status",
    minWidth: 180,
    maxWidth: 250,
    flex: 1,
    headerTooltip: true,
    renderCell: StatusCell,
  },
  {
    field: "action",
    headerName: "Action",
    flex: 1,
    minWidth: 100,
    renderCell: ActionCell,
  },
];
export const UserManagementRowData = [
  {
    id: 1,
    carrierId: 1,
    carrierName: "Swift Transportation",
    userProfile: "Admin",
    firstName: "John",
    lastName: "Doe",
    createdOn: "05-05-2026",
    updatedOn: "10-05-2026",
    primaryContactEmail: "john.doe@swift.com",
    status: "Active",
  },
  {
    id: 2,
    carrierId: 2,
    carrierName: "J.B. Hunt",
    userProfile: "Super Admin",
    firstName: "Sarah",
    lastName: "Smith",
    createdOn: "05-05-2025",
    updatedOn: "10-05-2025",
    primaryContactEmail: "sarah.smith@jbhunt.com",
    status: "Inactive",
  },
  {
    id: 3,
    carrierId: 3,
    carrierName: "Knight Transportation",
    userProfile: "User",
    firstName: "Michael",
    lastName: "Johnson",
    createdOn: "05-05-2025",
    updatedOn: "10-05-2025",
    primaryContactEmail: "michael.johnson@knight.com",
    status: "Active",
  },
  {
    id: 4,
    carrierId: 4,
    carrierName: "Werner Enterprises",
    userProfile: "Admin",
    firstName: "Emily",
    lastName: "Williams",
    createdOn: "05-05-2025",
    updatedOn: "10-05-2025",
    primaryContactEmail: "emily.williams@werner.com",
    status: "Active",
  },
  {
    id: 5,
    carrierId: 5,
    carrierName: "Schneider National",
    userProfile: "Admin",
    firstName: "David",
    lastName: "Brown",
    createdOn: "05-05-2025",
    updatedOn: "10-05-2025",
    primaryContactEmail: "david.brown@schneider.com",
    status: "Inactive",
  },
  {
    id: 6,
    carrierId: 6,
    carrierName: "XPO Logistics",
    userProfile: "Super Admin",
    firstName: "Olivia",
    lastName: "Taylor",
    createdOn: "05-05-2025",
    updatedOn: "10-05-2025",
    primaryContactEmail: "olivia.taylor@xpo.com",
    status: "Active",
  },
  {
    id: 7,
    carrierId: 7,
    carrierName: "FedEx Freight",
    userProfile: "Admin",
    firstName: "Daniel",
    lastName: "Anderson",
    createdOn: "05-05-2025",
    updatedOn: "10-05-2025",
    primaryContactEmail: "daniel.anderson@fedex.com",
    status: "Active",
  },
  {
    id: 8,
    carrierId: 8,
    carrierName: "Old Dominion",
    userProfile: "Admin",
    firstName: "Sophia",
    lastName: "Thomas",
    createdOn: "05-05-2025",
    updatedOn: "10-05-2025",
    primaryContactEmail: "sophia.thomas@odfl.com",
    status: "Inactive",
  },
];
